version: '2.1'
executors:
  php:
    docker:
      - image: php:7.4-cli-alpine
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: api-platform
          POSTGRES_DB: api_test
          POSTGRES_PASSWORD: ChangeMe
    working_directory: ~/repo

jobs:
  composer:
    executor: php
    steps:
      - run:
          name: Install alpine requirements for checkout
          command: apk add git openssh-client curl
      - run:
          name: Install Ruby
          command: |
            apk add --no-cache --virtual build-dependencies build-base
            apk -Uuv add --no-cache \
              make \
              curl \
              groff \
              less \
              nodejs-npm \
              bash \
              python2 \
              ruby
            apk --no-cache add ca-certificates wget bash \
                && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
            	&& wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk \
            	&& apk add glibc-2.29-r0.apk \
                && rm glibc-2.29-r0.apk
      - checkout
      - restore_cache:
          key: composer-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}-all
      - run:
          name: composer
          command: |
            if [[ ! -f vendor/autoload.php ]]; then
                curl https://getcomposer.org/composer.phar --location --silent  --output /usr/bin/composer; \
                chmod +x /usr/bin/composer; \
                composer self-update
                composer global require hirak/prestissimo; \
                composer install --no-progress --no-interaction; \
            fi
      - save_cache:
          key: composer-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}-all
          paths:
            - ./vendor
      - persist_to_workspace:
          root: .
          paths:
            - vendor

  phpstancs:
    executor: php
    steps:
      - run:
          name: Install alpine requirements for checkout
          command: apk add git openssh-client curl
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Cache warmup
          command: bin/console cache:warmup -e dev
      - run:
          name: phpstan
          command: vendor/bin/phpstan
      - run:
          name: phpcs
          command: vendor/bin/phpcs

  phpunit:
    executor: php
    steps:
      - run:
          name: Install alpine requirements for checkout.
          command: apk add git openssh-client curl
      - checkout
      - run:
          name: Install PostgreSQL client tools
          command: |
              apk add php-pdo_pgsql
      - run:
          name: Install and enable pdo_pgsql php extension
          command: |
              apk add postgresql-dev
              docker-php-ext-install pdo pdo_pgsql
      - attach_workspace:
          at: .
      - run:
          name: Cache warmup
          command: bin/console cache:warmup -e test
      - run:
          name: composer
          command: |
            curl https://getcomposer.org/composer.phar --location --silent  --output /usr/bin/composer; \
            chmod +x /usr/bin/composer; \
            composer self-update
      - run:
          name: Waiting for Postgres to be ready
          command: |
              for i in `seq 1 10`;
              do
                nc -z localhost 5432 && echo Success && exit 0
                echo -n .
                sleep 1
              done
              echo Failed waiting for Postgres && exit 1
      - run:
          name: phpunit
          command: vendor/bin/simple-phpunit
          environment:
            DATABASE_URL: postgres://api-platform:ChangeMe@localhost:5432/api_test

workflows:
  version: '2.1'
  Code quality:
    jobs:
      - composer
      - phpstancs:
          requires:
            - composer
      - phpunit:
          requires:
            - composer
